using System;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Input;
using Horizon.Game.GengDi.Core.ViewModels;
using Horizon.Game.GengDi.Tools.ExcelProcessor.Models;
using Horizon.Game.GengDi.Tools.ExcelProcessor.Services;

namespace Horizon.Game.GengDi.Tools.ExcelProcessor.ViewModels
{
    public class ExcelProcessorViewModel : ViewModelBase
    {
        private readonly ExcelReaderService _reader = new();
        private readonly ExcelMergeService _merger = new();
        private readonly MergeRequirementParser _parser = new();

        private ObservableCollection<ExcelSourceFile> _sourceFiles = new();
        private ObservableCollection<OperationLog> _operationLogs = new();
        private ObservableCollection<PreviewRow> _previewData = new();
        private ObservableCollection<string> _allColumns = new();

        private bool _isProcessing;
        private double _progress;
        private string _statusMessage = "就绪";
        private string _targetFilePath = string.Empty;
        private string _targetSheetName = "合并结果";
        private bool _removeDuplicates = true;
        private string _uniqueKeyColumns = string.Empty;
        private bool _skipHeader = true;
        private string _mergeRequirement = string.Empty;
        private string _parsedSummary = string.Empty;
        private bool _isConfigAutoGenerated;

        public Func<Task<IEnumerable<string>?>>? PickSourceFilesAsync { get; set; }
        public Func<Task<string?>>? PickTargetFileAsync { get; set; }

        public ExcelProcessorViewModel()
        {
            AddSourceCommand = new SimpleRelayCommand(async _ => await AddSourceFilesAsync());
            RemoveSourceCommand = new SimpleRelayCommand(obj => RemoveSourceFile(obj));
            SelectTargetCommand = new SimpleRelayCommand(async _ => await SelectTargetFileAsync());
            ExecuteMergeCommand = new SimpleRelayCommand(async _ => await ExecuteMergeAsync());
            ClearLogsCommand = new SimpleRelayCommand(_ => OperationLogs.Clear());
            ParseRequirementCommand = new SimpleRelayCommand(_ => ParseMergeRequirement());
        }

        public ICommand AddSourceCommand { get; }
        public ICommand RemoveSourceCommand { get; }
        public ICommand SelectTargetCommand { get; }
        public ICommand ExecuteMergeCommand { get; }
        public ICommand ClearLogsCommand { get; }
        public ICommand ParseRequirementCommand { get; }

        public ObservableCollection<ExcelSourceFile> SourceFiles
        {
            get => _sourceFiles;
            set => SetProperty(ref _sourceFiles, value);
        }

        public ObservableCollection<OperationLog> OperationLogs
        {
            get => _operationLogs;
            set => SetProperty(ref _operationLogs, value);
        }

        public ObservableCollection<PreviewRow> PreviewData
        {
            get => _previewData;
            set => SetProperty(ref _previewData, value);
        }

        public ObservableCollection<string> AllColumns
        {
            get => _allColumns;
            set => SetProperty(ref _allColumns, value);
        }

        public bool IsProcessing
        {
            get => _isProcessing;
            set => SetProperty(ref _isProcessing, value);
        }

        public double Progress
        {
            get => _progress;
            set => SetProperty(ref _progress, value);
        }

        public string StatusMessage
        {
            get => _statusMessage;
            set => SetProperty(ref _statusMessage, value);
        }

        public string TargetFilePath
        {
            get => _targetFilePath;
            set => SetProperty(ref _targetFilePath, value);
        }

        public string TargetSheetName
        {
            get => _targetSheetName;
            set => SetProperty(ref _targetSheetName, value);
        }

        public bool RemoveDuplicates
        {
            get => _removeDuplicates;
            set => SetProperty(ref _removeDuplicates, value);
        }

        public string UniqueKeyColumns
        {
            get => _uniqueKeyColumns;
            set => SetProperty(ref _uniqueKeyColumns, value);
        }

        public bool SkipHeader
        {
            get => _skipHeader;
            set => SetProperty(ref _skipHeader, value);
        }

        public string MergeRequirement
        {
            get => _mergeRequirement;
            set => SetProperty(ref _mergeRequirement, value);
        }

        public string ParsedSummary
        {
            get => _parsedSummary;
            set => SetProperty(ref _parsedSummary, value);
        }

        public bool IsConfigAutoGenerated
        {
            get => _isConfigAutoGenerated;
            set => SetProperty(ref _isConfigAutoGenerated, value);
        }

        private async Task AddSourceFilesAsync()
        {
            var pickFiles = PickSourceFilesAsync;
            if (pickFiles == null) return;

            var paths = await pickFiles();
            if (paths == null) return;

            foreach (var localPath in paths)
            {
                var existing = SourceFiles.FirstOrDefault(f => f.FilePath == localPath);
                if (existing != null) continue;

                var sourceFile = await _reader.AnalyzeFileAsync(localPath);
                if (sourceFile.IsLoaded)
                {
                    SourceFiles.Add(sourceFile);
                    UpdateAllColumns();
                    Log(LogLevel.Success, $"已添加文件: {sourceFile.FileName} ({sourceFile.RowCount} 行, {sourceFile.Columns.Count} 列)");
                }
                else
                {
                    Log(LogLevel.Error, $"文件加载失败: {sourceFile.ErrorMessage}");
                }
            }
        }

        private void RemoveSourceFile(object parameter)
        {
            if (parameter is ExcelSourceFile file)
            {
                SourceFiles.Remove(file);
                UpdateAllColumns();
                Log(LogLevel.Info, $"已移除文件: {file.FileName}");
            }
        }

        private async Task SelectTargetFileAsync()
        {
            var pickTarget = PickTargetFileAsync;
            if (pickTarget == null) return;

            var path = await pickTarget();
            if (!string.IsNullOrEmpty(path))
            {
                TargetFilePath = path;
                Log(LogLevel.Info, $"目标文件: {TargetFilePath}");
            }
        }

        private void ParseMergeRequirement()
        {
            if (string.IsNullOrWhiteSpace(MergeRequirement))
            {
                ParsedSummary = "";
                IsConfigAutoGenerated = false;
                ResetToDefaultConfig();
                return;
            }

            var parsed = _parser.Parse(MergeRequirement);
            ParsedSummary = parsed.Summary;
            IsConfigAutoGenerated = true;

            // Apply parsed settings
            if (!string.IsNullOrEmpty(parsed.TargetSheetName))
                TargetSheetName = parsed.TargetSheetName;

            RemoveDuplicates = parsed.RemoveDuplicates;
            UniqueKeyColumns = string.Join(",", parsed.UniqueKeyColumns);
            SkipHeader = parsed.SkipHeader;

            // Log the parsing result
            foreach (var note in parsed.Notes)
            {
                Log(LogLevel.Info, note);
            }

            Log(LogLevel.Success, $"配置已自动生成: {parsed.Summary}");
        }

        private void ResetToDefaultConfig()
        {
            TargetSheetName = "合并结果";
            RemoveDuplicates = true;
            UniqueKeyColumns = string.Empty;
            SkipHeader = true;
        }

        private async Task ExecuteMergeAsync()
        {
            if (!SourceFiles.Any())
            {
                StatusMessage = "请先添加源文件";
                return;
            }

            if (string.IsNullOrWhiteSpace(TargetFilePath))
            {
                StatusMessage = "请选择目标文件保存路径";
                return;
            }

            IsProcessing = true;
            Progress = 0;
            StatusMessage = "正在处理...";
            PreviewData.Clear();
            OperationLogs.Clear();

            // Re-parse requirement before merge to ensure latest settings
            if (!string.IsNullOrWhiteSpace(MergeRequirement))
            {
                ParseMergeRequirement();
            }

            var config = new MergeConfig
            {
                SourceFilePaths = SourceFiles.Select(f => f.FilePath).ToList(),
                TargetFilePath = TargetFilePath,
                TargetSheetName = TargetSheetName,
                RemoveDuplicates = RemoveDuplicates,
                UniqueKeyColumns = string.IsNullOrWhiteSpace(UniqueKeyColumns)
                    ? new List<string>()
                    : UniqueKeyColumns.Split(',', StringSplitOptions.RemoveEmptyEntries)
                        .Select(s => s.Trim()).ToList(),
                SkipHeader = SkipHeader
            };

            try
            {
                Progress = 30;
                var result = await _merger.MergeAsync(config);

                Progress = result.Success ? 100 : 50;
                StatusMessage = result.Message;

                foreach (var row in result.Preview)
                    PreviewData.Add(row);

                foreach (var log in _merger.Logs)
                    OperationLogs.Add(log);
            }
            finally
            {
                IsProcessing = false;
            }
        }

        private void UpdateAllColumns()
        {
            var columns = new HashSet<string>();
            foreach (var file in SourceFiles)
            {
                foreach (var col in file.Columns)
                    columns.Add(col.Name);
            }
            AllColumns = new ObservableCollection<string>(columns);
        }

        private void Log(LogLevel level, string message)
        {
            OperationLogs.Add(new OperationLog
            {
                Timestamp = DateTime.Now,
                Level = level,
                Message = message
            });
        }
    }

    internal class SimpleRelayCommand : ICommand
    {
        private readonly Action<object> _execute;
        public SimpleRelayCommand(Action<object> execute) { _execute = execute; }
        public bool CanExecute(object parameter) => true;
        public void Execute(object parameter) => _execute(parameter);
        public event EventHandler CanExecuteChanged;
    }
}
