<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>d0c7182e-420b-44d7-8c8f-42b8a1738cd3</UserSecretsId>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile></DocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\Games\GameConfigController.cs" />
    <Compile Remove="Controllers\Games\GameUserRoleController.cs" />
    <Compile Remove="Controllers\Users\UserController .cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="appsettings.json" />
    <Content Remove="Configs\ApiLog.config" />
    <Content Remove="Configs\CommonLog.config" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Configs\ApiLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Configs\CommonLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageReference Include="IdentityServer4" Version="4.1.2" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.DependencyValidation.Analyzers" Version="0.11.0" />
    <PackageReference Include="Microsoft.Orleans.Client" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Core" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Serialization" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Serialization.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Serialization.NewtonsoftJson" Version="10.0.1" />
    <PackageReference Include="NetCoreServer" Version="8.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />   
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horizon.Core.Abstract\Horizon.Core.Abstract.csproj" />
    <ProjectReference Include="..\Horizon.Core\Horizon.Core.csproj" />
    <ProjectReference Include="..\Horizon.Game.Message\Horizon.Game.Message.csproj" />
    <ProjectReference Include="..\Horizon.IM.Message\Horizon.IM.Message.csproj" />
    <ProjectReference Include="..\Horizon.Model\Horizon.Model.csproj" />
    <ProjectReference Include="..\Horizon.Orleans.Grains\Horizon.Orleans.Grains.csproj" />
    <ProjectReference Include="..\Horizon.Orleans.Interface\Horizon.Orleans.Interface.csproj" />
    <ProjectReference Include="..\Horizon.Share\Horizon.Share.csproj" />
    <ProjectReference Include="..\Horizon.Strategy.Storage.Redis\Horizon.Strategy.Storage.Redis.csproj" />
    <ProjectReference Include="..\Horizon.IoT.MQTT\Horizon.IoT.MQTT.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Games\" />
    <Folder Include="Controllers\Users\" />
  </ItemGroup>


</Project>
