using Horizon.Game.Message.Enums;
using Horizon.Game.Message.Network;
using MemoryPack;
using Orleans;

namespace Horizon.Game.Message
{
    /// <summary>
    /// 消息联合体基类
    /// 所有网络消息类型都应继承此类
    /// </summary>
    [MemoryPackable(SerializeLayout.Explicit)]
    [GenerateSerializer]
    // 网络消息类的MemoryPackUnion注解
    [MemoryPackUnion(0, typeof(LoginRequest))]
    [MemoryPackUnion(1, typeof(LoginResponse))]
    [MemoryPackUnion(2, typeof(RegisterRequest))]
    [MemoryPackUnion(3, typeof(RegisterResponse))]
    [MemoryPackUnion(4, typeof(CharacterInfo))]
    [MemoryPackUnion(5, typeof(Position))]
    [MemoryPackUnion(6, typeof(AppearanceInfo))]
    [MemoryPackUnion(7, typeof(CreateCharacterRequest))]
    [MemoryPackUnion(8, typeof(CreateCharacterResponse))]
    [MemoryPackUnion(9, typeof(EnterGameRequest))]
    [MemoryPackUnion(10, typeof(EnterGameResponse))]
    [MemoryPackUnion(11, typeof(DeleteCharacterRequest))]
    [MemoryPackUnion(12, typeof(DeleteCharacterResponse))]
    [MemoryPackUnion(13, typeof(MoveRequest))]
    [MemoryPackUnion(14, typeof(MoveResponse))]
    [MemoryPackUnion(15, typeof(ServerInfo))]
    [MemoryPackUnion(16, typeof(AttackMessage))]
    [MemoryPackUnion(17, typeof(SkillCastMessage))]
    [MemoryPackUnion(18, typeof(DamageMessage))]
[MemoryPackUnion(19, typeof(SessionInfoMessage))]
[MemoryPackUnion(20, typeof(CharacterListRequest))]
[MemoryPackUnion(21, typeof(CharacterListResponse))]
[MemoryPackUnion(22, typeof(ValidateCharacterNameRequest))]
[MemoryPackUnion(23, typeof(ValidateCharacterNameResponse))]
[MemoryPackUnion(24, typeof(AuthenticationError))]
[MemoryPackUnion(25, typeof(ZoneAndServerInfo))]
[MemoryPackUnion(26, typeof(ZoneInfo))]
[MemoryPackUnion(27, typeof(HeartbeatMessage))]
[MemoryPackUnion(28, typeof(HeartbeatResponse))]
[MemoryPackUnion(29, typeof(ChatMessage))]
[MemoryPackUnion(30, typeof(SkillInfo))]
[MemoryPackUnion(31, typeof(ItemInfo))]
[MemoryPackUnion(32, typeof(EquipmentInfoMessage))]
[MemoryPackUnion(33, typeof(InventoryUpdateMessage))]
    [MemoryPackUnion(34, typeof(DeathMessage))]
    [MemoryPackUnion(35, typeof(ResurrectMessage))]
    [MemoryPackUnion(36, typeof(QingGongMessage))]
    [MemoryPackUnion(37, typeof(NeiGongMessage))]
    [MemoryPackUnion(38, typeof(ComboAttackMessage))]
    [MemoryPackUnion(39, typeof(DefenseMessage))]
    [MemoryPackUnion(40, typeof(AttributeUpdateMessage))]
    [MemoryPackUnion(41, typeof(ChatHistoryRequest))]
    [MemoryPackUnion(42, typeof(ChatHistoryResponse))]
    [MemoryPackUnion(43, typeof(FriendInfo))]
    [MemoryPackUnion(44, typeof(AddFriendRequest))]
    [MemoryPackUnion(45, typeof(AddFriendResponse))]
    [MemoryPackUnion(46, typeof(FriendListUpdateMessage))]
    [MemoryPackUnion(47, typeof(TeamInfo))]
    [MemoryPackUnion(48, typeof(TeamMemberInfo))]
    [MemoryPackUnion(49, typeof(CreateTeamRequest))]
    [MemoryPackUnion(50, typeof(CreateTeamResponse))]
    [MemoryPackUnion(51, typeof(JoinTeamRequest))]
    [MemoryPackUnion(52, typeof(JoinTeamResponse))]
    [MemoryPackUnion(53, typeof(GuildInfo))]
    [MemoryPackUnion(54, typeof(CreateGuildRequest))]
    [MemoryPackUnion(55, typeof(CreateGuildResponse))]
    [MemoryPackUnion(56, typeof(JoinGuildRequest))]
    [MemoryPackUnion(57, typeof(JoinGuildResponse))]
    [MemoryPackUnion(58, typeof(QuestInfo))]
    [MemoryPackUnion(59, typeof(QuestObjective))]
    [MemoryPackUnion(60, typeof(QuestUpdateMessage))]
    [MemoryPackUnion(61, typeof(AcceptQuestRequest))]
    [MemoryPackUnion(62, typeof(AcceptQuestResponse))]
    [MemoryPackUnion(63, typeof(CompleteQuestRequest))]
    [MemoryPackUnion(64, typeof(CompleteQuestResponse))]
    [MemoryPackUnion(65, typeof(ItemChangeInfo))]
    [MemoryPackUnion(66, typeof(EquipItemMessage))]
    [MemoryPackUnion(67, typeof(WeaponSwitchMessage))]
    [MemoryPackUnion(68, typeof(UseItemRequest))]
    [MemoryPackUnion(69, typeof(UseItemResponse))]
    [MemoryPackUnion(70, typeof(ItemEffect))]
    [MemoryPackUnion(71, typeof(EquipmentEnhanceRequest))]
    [MemoryPackUnion(72, typeof(EquipmentEnhanceResponse))]
    [MemoryPackUnion(73, typeof(EquipmentRefineRequest))]
    [MemoryPackUnion(74, typeof(EquipmentRefineResponse))]
    [MemoryPackUnion(75, typeof(CraftingRequest))]
    [MemoryPackUnion(76, typeof(CraftingResponse))]
    [MemoryPackUnion(77, typeof(AttributeInheritanceRequest))]
    [MemoryPackUnion(78, typeof(AttributeInheritanceResponse))]
    [MemoryPackUnion(79, typeof(WuXingCraftingRequest))]
    [MemoryPackUnion(80, typeof(WuXingCraftingResponse))]
    [MemoryPackUnion(81, typeof(PlayerAnimationMessage))]
    [MemoryPackUnion(82, typeof(SystemMessage))]
    [MemoryPackUnion(83, typeof(ServerListRequest))]
    [MemoryPackUnion(84, typeof(LearnSkillRequest))]
    [MemoryPackUnion(85, typeof(LearnSkillResponse))]
    [MemoryPackUnion(86, typeof(SkillCooldownQueryRequest))]
    [MemoryPackUnion(87, typeof(SkillCooldownQueryResponse))]
    [MemoryPackUnion(88, typeof(SkillCooldownUpdateMessage))]
    [MemoryPackUnion(89, typeof(SkillProficiencyQueryRequest))]
    [MemoryPackUnion(90, typeof(SkillProficiencyQueryResponse))]
    [MemoryPackUnion(91, typeof(SkillProficiencyUpdateMessage))]
    [MemoryPackUnion(92, typeof(UpgradeSkillRequest))]
    [MemoryPackUnion(93, typeof(UpgradeSkillResponse))]
    [MemoryPackUnion(94, typeof(SkillLevelUpdateMessage))]
    [MemoryPackUnion(95, typeof(SkillSlotInfo))]
    [MemoryPackUnion(96, typeof(UpdateSkillSlotRequest))]
    [MemoryPackUnion(97, typeof(UpdateSkillSlotResponse))]
    [MemoryPackUnion(98, typeof(SectInfoMessage))]
    [MemoryPackUnion(99, typeof(JoinSectRequest))]
    [MemoryPackUnion(100, typeof(JoinSectResponse))]
    [MemoryPackUnion(101, typeof(SectSkillMessage))]
    [MemoryPackUnion(102, typeof(SectQuestMessage))]
    [MemoryPackUnion(103, typeof(ReputationUpdateMessage))]
    [MemoryPackUnion(104, typeof(ChivalryPointUpdateMessage))]
    [MemoryPackUnion(105, typeof(DuelRequest))]
    [MemoryPackUnion(106, typeof(DuelResponse))]
    [MemoryPackUnion(107, typeof(SwornBrotherRequest))]
    [MemoryPackUnion(108, typeof(SwornBrotherResponse))]
    [MemoryPackUnion(109, typeof(MasterApprenticeRequest))]
    [MemoryPackUnion(110, typeof(MasterApprenticeResponse))]
    [MemoryPackUnion(111, typeof(SystemNotificationMessage))]
    [MemoryPackUnion(112, typeof(SystemAnnouncementMessage))]
    [MemoryPackUnion(113, typeof(ErrorMessage))]
    [MemoryPackUnion(114, typeof(ServerStatusMessage))]
    [MemoryPackUnion(115, typeof(ConfigUpdateMessage))]
    [MemoryPackUnion(116, typeof(VersionUpdateMessage))]
    [MemoryPackUnion(117, typeof(LogMessage))]
    [MemoryPackUnion(118, typeof(InventoryInfo))]
    [MemoryPackUnion(119, typeof(CraftingRecipe))]
    [MemoryPackUnion(120, typeof(MapPlayer))]
    [MemoryPackUnion(121, typeof(GuildMember))]
    [MemoryPackUnion(122, typeof(PlayerSyncMessage))]
    [MemoryPackUnion(123, typeof(WorldStateSyncMessage))]
    [MemoryPackUnion(124, typeof(WorldEvent))]
    [MemoryPackUnion(125, typeof(NpcSyncMessage))]
    [MemoryPackUnion(126, typeof(ItemDropMessage))]
    [MemoryPackUnion(127, typeof(SystemCommandMessage))]
    [MemoryPackUnion(128, typeof(SystemCommandResultMessage))]
    [MemoryPackUnion(129, typeof(ServerManagementMessage))]
    [MemoryPackUnion(130, typeof(PlayerManagementMessage))]
    [MemoryPackUnion(131, typeof(GameEventMessage))]
    // [MemoryPackUnion(132, typeof(SectInfoMessage))] // Duplicate removed, already defined at index 98
    [MemoryPackUnion(133, typeof(SectSkillInfo))]
    [MemoryPackUnion(134, typeof(SkillPrerequisites))]
    [MemoryPackUnion(135, typeof(GuildInfoMessage))]
    [MemoryPackUnion(136, typeof(GuildSkillInfo))]
    [MemoryPackUnion(137, typeof(MartialArtsManualMessage))]
    [MemoryPackUnion(138, typeof(MartialArtsEffect))]
    [MemoryPackUnion(139, typeof(WuXingSystemMessage))]
    public abstract partial class MessageUnion : INetworkMessage
    {
        [MemoryPackOrder(254)]
        [Id(254)]
        public ServiceType ServiceType { get; set; }

        [MemoryPackOrder(255)]
        [Id(255)]
        public MessageType Type { get; set; }
    }
}