<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BI\**" />
    <Compile Remove="Longlearn\**" />
    <Compile Remove="Web\**" />
    <EmbeddedResource Remove="BI\**" />
    <EmbeddedResource Remove="Longlearn\**" />
    <EmbeddedResource Remove="Web\**" />
    <None Remove="BI\**" />
    <None Remove="Longlearn\**" />
    <None Remove="Web\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DependencyValidation.Analyzers" Version="0.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horizon.Core.Abstract\Horizon.Core.Abstract.csproj" />
    <ProjectReference Include="..\Horizon.Core\Horizon.Core.csproj" />
    <ProjectReference Include="..\Horizon.Game.Message\Horizon.Game.Message.csproj" />
    <ProjectReference Include="..\Horizon.Share\Horizon.Share.csproj" />
  </ItemGroup>

</Project>
