<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="yqubukcb.2xa~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Alipay.AopSdk.Core" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Orleans.Runtime" />
	  <PackageReference Include="Microsoft.Orleans.Core" />
	  <PackageReference Include="Microsoft.Orleans.Core.Abstractions" />
	  <PackageReference Include="Microsoft.Orleans.Persistence.Redis" />
	  <PackageReference Include="Microsoft.Orleans.Sdk" />
	  <PackageReference Include="Microsoft.Orleans.CodeGenerator">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Orleans.Streaming" />
	  <PackageReference Include="Microsoft.Orleans.Streaming.EventHubs" />
    <PackageReference Include="MongoDB.Driver" />
	  <PackageReference Include="MemoryPack.Core" />
	  <PackageReference Include="MemoryPack.Generator" PrivateAssets="all" />
	  <PackageReference Include="Polly" />
    <PackageReference Include="MiniExcel" />
    <PackageReference Include="SKIT.FlurlHttpClient.Wechat.TenpayV3" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.SemanticKernel" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <ProjectReference Include="..\Horizon.Core\Horizon.Core.csproj" />
    <ProjectReference Include="..\Horizon.Entities\Horizon.Entities.csproj" />
    <ProjectReference Include="..\Horizon.Game.Message\Horizon.Game.Message.csproj" />
    <ProjectReference Include="..\Horizon.IM.Message\Horizon.IM.Message.csproj" />
    <ProjectReference Include="..\Horizon.Mapper\Horizon.Mapper.csproj" />
    <ProjectReference Include="..\Horizon.Model\Horizon.Model.csproj" />
    <ProjectReference Include="..\Horizon.Orleans.Interface\Horizon.Orleans.Interface.csproj" />
    <ProjectReference Include="..\Horizon.Share\Horizon.Share.csproj" />
    <ProjectReference Include="..\Horizon.Strategy.Storage.Redis\Horizon.Strategy.Storage.Redis.csproj" />
    <ProjectReference Include="..\Horizon.AI.Kernel\Horizon.AI.Kernel.csproj" />
    <ProjectReference Include="..\Horizon.IoT.MQTT\Horizon.IoT.MQTT.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Horizon.Game.Gateway.Tests" />
  </ItemGroup>

</Project>
