<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="K4os.Compression.LZ4" />
    <PackageReference Include="MemoryPack.Core" />
    <PackageReference Include="MemoryPack.Generator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Orleans.Client" />
    <PackageReference Include="Microsoft.Orleans.Core" />
    <PackageReference Include="Microsoft.Orleans.Serialization" />
    <PackageReference Include="TouchSocket" />
    <PackageReference Include="TouchSocket.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horizon.IM.Message\Horizon.IM.Message.csproj" />
    <ProjectReference Include="..\Horizon.Orleans.Interface\Horizon.Orleans.Interface.csproj" />
  </ItemGroup>

</Project>