<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack.Core" />
    <PackageReference Include="MemoryPack.Generator" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Microsoft.Orleans.Core" />
	  <PackageReference Include="Microsoft.Orleans.Persistence.Redis" />
	  <PackageReference Include="Microsoft.Orleans.Streaming" />
	  <PackageReference Include="Microsoft.Orleans.Streaming.EventHubs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horizon.Game.Message\Horizon.Game.Message.csproj" />
    <ProjectReference Include="..\Horizon.IM.Message\Horizon.IM.Message.csproj" />
    <ProjectReference Include="..\Horizon.Share\Horizon.Share.csproj" />
  </ItemGroup>

</Project>
