// <auto-generated />
using System;
using Horizon.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Horizon.Entities.Migrations.BasicEntity
{
    [DbContext(typeof(BasicEntityContext))]
    [Migration("20231009172517_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Horizon.Model.Apps", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AppType")
                        .HasColumnType("int")
                        .HasComment("应用类型");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用负责人");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("应用上线时间");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用简述");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用网站首页地址");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用Logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.Property<DateTime?>("OverDate")
                        .HasColumnType("datetime2")
                        .HasComment("应用下线时间");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("团队");

                    b.HasKey("Id");

                    b.ToTable("Basic_Sys_Applications");
                });

            modelBuilder.Entity("Horizon.Model.Basic.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasComment("分类Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("简介");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名称");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("int")
                        .HasComment("组织机构类型");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("父级");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("Basic_Sys_Organization");
                });

            modelBuilder.Entity("Horizon.Model.Basic.OrganizationCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("简介");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名称");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("父级");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Basic_Sys_OrganizationCategory");
                });

            modelBuilder.Entity("Horizon.Model.Basic.PassportFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCreating")
                        .HasColumnType("bit")
                        .HasComment("是否正在生成中");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<DateTime>("LastTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后一次生成时间");

                    b.Property<long>("Total")
                        .HasColumnType("bigint")
                        .HasComment("生成总数");

                    b.HasKey("Id");

                    b.ToTable("Basic_Sys_PassportFlag", t =>
                        {
                            t.HasComment("生成通行证开关表");
                        });
                });

            modelBuilder.Entity("Horizon.Model.Basic.PassportIds", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ApplyTime")
                        .HasColumnType("datetime2")
                        .HasComment("应用时间");

                    b.Property<DateTime>("CreatingTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.HasKey("Id");

                    b.ToTable("Basic_Sys_PassportIds");
                });

            modelBuilder.Entity("Horizon.Model.DistrictDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<long>("APPId")
                        .HasColumnType("bigint")
                        .HasComment("应用Id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar")
                        .HasColumnOrder(7)
                        .HasComment("数据账号");

                    b.Property<int>("AppType")
                        .HasColumnType("int")
                        .HasComment("数据应用类型");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint")
                        .HasComment("区域Id");

                    b.Property<string>("COMMENTS")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnOrder(10)
                        .HasComment("备注");

                    b.Property<int>("DDbType")
                        .HasColumnType("int")
                        .HasColumnOrder(4)
                        .HasComment("数据库类型");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(39)
                        .HasColumnType("varchar")
                        .HasColumnOrder(5)
                        .HasComment("数据库IP");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<DateTime>("MODITIME")
                        .HasColumnType("datetime")
                        .HasColumnOrder(11)
                        .HasComment("时间戳,分库建立时间");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnOrder(8)
                        .HasComment("数据密码");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnOrder(6)
                        .HasComment("数据库端口");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasComment("服务Id");

                    b.HasKey("Id");

                    b.ToTable("Basic_Sys_DDBs");
                });

            modelBuilder.Entity("Horizon.Model.Labe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("标签");

                    b.HasKey("Id");

                    b.ToTable("Basic_Sys_Labe");
                });

            modelBuilder.Entity("Horizon.Model.MemberLabe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<long>("LabeId")
                        .HasColumnType("bigint")
                        .HasComment("标签Id");

                    b.Property<string>("PassportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("通行证");

                    b.HasKey("Id");

                    b.HasIndex("LabeId");

                    b.HasIndex("PassportId");

                    b.ToTable("Basic_Sys_MemberLabe");
                });

            modelBuilder.Entity("Horizon.Model.Passport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("登录密码");

                    b.HasKey("Id");

                    b.ToTable("Basic_Sys_Passport");
                });

            modelBuilder.Entity("Horizon.Model.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasComment("区域行政等级");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("区域名称");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasComment("上级区域编号");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("区域简称");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("状态");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Basic_Sys_Region");
                });

            modelBuilder.Entity("Horizon.Model.RoleInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint")
                        .HasComment("系统用户Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("简述");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("角色名称");

                    b.HasKey("Id");

                    b.ToTable("Basics_Sys_Role");
                });

            modelBuilder.Entity("Horizon.Model.RolePrivilegeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<long>("Privilege")
                        .HasColumnType("bigint")
                        .HasComment("权限值");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("角色Id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Basics_Sys_RolePrivilege");
                });

            modelBuilder.Entity("Horizon.Model.SysManager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户名");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("密码");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("角色");

                    b.HasKey("Id");

                    b.ToTable("Basics_Sys_SysManager");
                });

            modelBuilder.Entity("Horizon.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("地址");

                    b.Property<long>("AppId")
                        .HasColumnType("bigint");

                    b.Property<int>("AppType")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户头像");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Constellation")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户简介");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("邮箱");

                    b.Property<DateTime?>("FrozenDate")
                        .HasColumnType("datetime2")
                        .HasComment("冻结时间");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("使用地址");

                    b.Property<string>("IdCard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("身份Id号");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnOrder(59);

                    b.Property<DateTime?>("LastLoginDate")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasComment("最后登录时间");

                    b.Property<long>("LoginNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasComment("登录次数");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("真实姓名");

                    b.Property<string>("NickName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("昵称");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PassportId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("PassportType")
                        .HasColumnType("int")
                        .HasComment("当前用户通行证类型");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("电话");

                    b.Property<string>("RegionPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Basic_Sys_User");
                });

            modelBuilder.Entity("Horizon.Model.Basic.Organization", b =>
                {
                    b.HasOne("Horizon.Model.Basic.OrganizationCategory", "Category")
                        .WithMany("Organizations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Horizon.Model.Basic.Organization", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Horizon.Model.Basic.OrganizationCategory", b =>
                {
                    b.HasOne("Horizon.Model.Basic.OrganizationCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Horizon.Model.MemberLabe", b =>
                {
                    b.HasOne("Horizon.Model.Labe", "LabeInfo")
                        .WithMany("MemberLabes")
                        .HasForeignKey("LabeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Horizon.Model.Passport", "PassportInfo")
                        .WithMany("MemberLabes")
                        .HasForeignKey("PassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabeInfo");

                    b.Navigation("PassportInfo");
                });

            modelBuilder.Entity("Horizon.Model.Region", b =>
                {
                    b.HasOne("Horizon.Model.Region", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Horizon.Model.RolePrivilegeInfo", b =>
                {
                    b.HasOne("Horizon.Model.RoleInfo", "RoleInfo")
                        .WithMany("RolePrivilegeInfo")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleInfo");
                });

            modelBuilder.Entity("Horizon.Model.Basic.OrganizationCategory", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("Horizon.Model.Labe", b =>
                {
                    b.Navigation("MemberLabes");
                });

            modelBuilder.Entity("Horizon.Model.Passport", b =>
                {
                    b.Navigation("MemberLabes");
                });

            modelBuilder.Entity("Horizon.Model.RoleInfo", b =>
                {
                    b.Navigation("RolePrivilegeInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
